In [4]:
##Type Of Array,1D Array/vector
import numpy as np
a=np.array([1,2,3,4])
print(type(a))
print (a)




<class 'numpy.ndarray'>
[1 2 3 4]


In [6]:
#2D Array /matrics

b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
#3D array/tensor

c=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [12]:
#dtype
f=np.array([1,2,3],dtype=float)
g=np.array([1,0,3],dtype=bool)
h=np.array([4,5,6],dtype=complex)
print(f,g,h)

[1. 2. 3.] [ True False  True] [4.+0.j 5.+0.j 6.+0.j]


In [14]:
#np.arange 
np.arange(1,11,2)



array([1, 3, 5, 7, 9])

In [17]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
#np.ones & np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#np.random
np.random.random((3,4))

array([[0.4244084 , 0.02289685, 0.65809955, 0.46695695],
       [0.19950578, 0.08129326, 0.83272255, 0.19138368],
       [0.61024307, 0.61097998, 0.41263428, 0.72979738]])

In [21]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#numpy attribute


In [40]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
#ndim
a1.ndim
a2.ndim
a3.ndim

3

In [32]:
#shape
a1.shape
a2.shape
a3.shape
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
#size
print (a2.size)
a2


12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [42]:
#itemsize
a1.itemsize
a3.itemsize


8

In [43]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


#Changing datatype


In [46]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

##Array Operation

In [48]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [50]:
#scaler operation
#arithmatic 
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [53]:
#relational
a1==5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [55]:
#vecetor operations
#arithmatic
a1+a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [59]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1


array([[71., 68., 16.],
       [68., 50., 39.],
       [22., 93., 23.]])

In [67]:
#max/min/sum/prod
np.min(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis=1)
np.max(a1,axis=0)



array([71., 93., 39.])

In [70]:
#mean/median/std/var
np.mean(a1)
np.median(a1,axis=0)
np.std(a1)
np.var(a1)

np.float64(636.4444444444445)

In [72]:
#trigonomatric function
np.sin(a1)
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [74]:
#log and axponents
np.log(a1)
np.exp(a1)

array([[6.83767123e+30, 3.40427605e+29, 8.88611052e+06],
       [3.40427605e+29, 5.18470553e+21, 8.65934004e+16],
       [3.58491285e+09, 2.45124554e+40, 9.74480345e+09]])

In [76]:
#round/flor.ceil
np.round(np.random.random((2,3))*100)


array([[ 9., 91., 19.],
       [45., 33., 64.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

In [2]:
#indexing and slicing
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a1[-1]

np.int64(9)

In [7]:
a2[1,0]

np.int64(4)

In [8]:
a3[1,0,1]

np.int64(5)

In [9]:
a3[0,1,0]

np.int64(2)

In [11]:
a1[2:5:2]

array([2, 4])

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a2[:,2]

array([ 2,  6, 10])

In [16]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [17]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [21]:
#iterating
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [24]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [25]:
a2
for i in a2:
   print (i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [26]:
a3
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [28]:
#Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
#ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [33]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
#splitting
np.hsplit(a4,2)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]